[source]
name = "source_boil-hello-world"
description = "Source for official Boilermake Hello World templates"
backend = "sql::sqlite"

[[templates]]
repo = "https://github.com/yeajustmars/boil-hello-world"
name = "hello-world"
lang = "bash"
branch = "main"

[[templates]]
repo = "https://github.com/yeajustmars/boil-hello-world"
name = "hello-world"
lang = "clojure"
branch = "main"

[[templates]]
repo = "https://github.com/yeajustmars/boil-hello-world"
name = "hello-world"
lang = "javascript"
branch = "main"

[[templates]]
repo = "https://github.com/yeajustmars/boil-hello-world"
name = "hello-world"
lang = "python"
branch = "main"

[[templates]]
repo = "https://github.com/yeajustmars/boil-hello-world"
name = "hello-world"
lang = "rust"
branch = "main"
