[project]
name = "hello-boilermaker"
description = "Simple Hello World with Boilermaker"
version = "0.1.0"
default_lang = "rust"
repository = "https://github.com/yeajustmars/boil-hello-world"
authors = ["yeajustmars"]
keywords = ["boilermaker", "example", "hello-world"]
website = "https://github.com/yeajustmars/boil-hello-world"
license = "MIT"

[variables]
welcome_message = "Hello, World!"
